version: '3.8'
services:
  node:
    image: sahilnarwal2111/reactapp4:latest
    container_name: myapp-node
    volumes:
      - ./app:/myapp
    working_dir: /myapp
    ports:
      - 3000:80

  python:
    image: sahilnarwal2111/newsbot:latest
    container_name: myapp-python
    volumes:
      - ./app:/app
    working_dir: /app
    
