version: '3.8'
services:
  node:
    image: frontend-final-ad
    container_name: myapp-node
    volumes:
      - ./app:/myapp
    working_dir: /myapp
    ports:
      - 3000:80

  python:
    image: polybot-final
    container_name: myapp-python
    volumes:
      - ./app:/app
    working_dir: /app
    
